### ISSUE TITLE
Feature request: Include CUDA toolkit in NVIDIA image

### ISSUE THREAD

**Issue by kbdharun** [Vanilla-OS/nvidia-image#23]
Continuing https://www.reddit.com/r/vanillaos/comments/1cjxtgp/nvidia_cuda_and_machine_learning/

CUDA is NVIDIA's proprietary parallel computing platform and application programming interface that allows software to use certain types of graphics processing units for accelerated general-purpose processing, an approach called general-purpose computing on GPUs.

It is very useful for Machine learning and software development. It significantly speeds up a lot of the processes like building, modelling and compiling.

Adding it to the NVIDIA image is as simple as adding `nvidia-cuda-toolkit` (https://packages.vanillaos.org/package/nvidia-cuda-toolkit) to the `recipe.yml` file. This addition would add 163 MBs of size to the image but would be useful to a significant portion of the users using this image.

**Comment by mirkobrombin** [comment]
Duplicate of https://github.com/Vanilla-OS/nvidia-image/issues/19

**Comment by kbdharun** [comment]
> Duplicate of #19

No, container toolkit is a separate package, will look into it and maybe add it https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html.

**Comment by taukakao** [comment]
The Cuda toolkit takes up a lot of space. We can't afford that in the standard install. This is being reverted.
