### ISSUE TITLE
NVIDIA card not showing up in Gnome Settings

### ISSUE THREAD

**Issue by RaulKong898** [Vanilla-OS/nvidia-image#26]
### Issue Description

NVIDIA video card does not appear in the "About" section of "System Details": My NVIDIA video card does not appear in the "Graphics 1" section of the system details. Instead, I see the AMD Radeon video card, the one integrated into the processor. Not sure if it's a viewing error or something else. However, the NVIDIA control panel is accessible and shows me the video card settings.
![Screenshot from 2024-05-04 18-24-51](https://github.com/Vanilla-OS/live-iso/assets/121046976/0936b858-d1bd-46e9-be17-42fdacfde596)
![Screenshot from 2024-05-04 18-27-25](https://github.com/Vanilla-OS/live-iso/assets/121046976/3df085a2-bdd6-44ca-b84c-b0792b3f389f)

### Steps to Reproduce

Open “System details” from the settings menu.
Go to the "About" section.
Check if the NVIDIA video card appears in the “Graphics 1” section.

### On what version of Vanilla OS this happens?

Unreleased

**Comment by taukakao** [comment]
Sorry, but Github issues need to be focused on one topic to be manageable, so I removed the stuff about sideloading. 
You can of course create another bug report for that.

**Comment by taukakao** [comment]
Most likely, this is just a limitation of Gnome Settings. 
I think this is only really an issue if the Graphics card doesn't work with Vanilla OS.

**Comment by mirkobrombin** [comment]
Hi, Nvidia settings is running and detecting both the drivers and the GPU, so I think this is a bug in GNOME Settings and must be reported to them.
