### ISSUE TITLE
Apps appear to open however there are no windows for them. Just the indicator in the dash changes, nothing opens

### ISSUE THREAD

**Issue by Nojinverse** [Vanilla-OS/nvidia-image#31]
### Issue Description

![image](https://github.com/Vanilla-OS/nvidia-image/assets/52561379/f16b599a-7ba8-4928-aa8d-2e3b4fdbd253)

high jacking okibi issue from discord.

newest update results in apps appearing to open but nothing happens. just the indicator in the dash but nothing happens.

### Steps to Reproduce

update to the newest version

### On what version of Vanilla OS this happens?

beta / unstable

**Comment by mirkobrombin** [comment]
We just dropped a new release, can you try that?

**Comment by Nojinverse** [comment]
The one of the newer versions seem to have solved the issue.
