### ISSUE TITLE
Some 40-series GPUs are not supported

### ISSUE THREAD

**Issue by abarnes6** [Vanilla-OS/nvidia-image#36]
### Issue Description

I am unable to install VanillaOS-2-testing.20240625 using a 4070 Ti for output. I get a black screen with text that reads "Failed to register i2c client MSFT8000:00 at 0x40 (-16)" and "hub 8-0:1.0: config failed, hub doesn't have any ports! (err -19)".

### Steps to Reproduce

- Have a 4070 Ti card
- Plug monitor into said card
- Boot into VanillaOS-2-testing.20240625.iso
- Select any of the three options (normal start, safe graphics, nouveau unloaded)
- Observe the lack of a desktop environment or terminal

### On what version of Vanilla OS this happens?

Unreleased

**Comment by taukakao** [comment]
Btw. I'm not sure if the firmware is new enough to support this card but it might be worth a shot now.

**Comment by abarnes6** [comment]
@taukakao I'm not actually convinced its a driver issue in my case anyway. Debian sid said it couldn't find a monitor when booting from the iso copied to a drive partition. I also tried a 2GB usb stick, but the same thing happened. I will try a proper 8gb stick when I get the chance.
