### ISSUE TITLE
gdm fails to load

### ISSUE THREAD

**Issue by taukakao** [Vanilla-OS/nvidia-image#38]
Systemd gets stuck and freezes the system while starting gdm.
Multiple user reports indicate that this is the case.

**Comment by mirkobrombin** [comment]
Tested on both a GTX 1660 and an RTX 1050 with no issues. Need some more details to plan a fix for the stable, otherwise we'll have to postpone this fix.

**Comment by taukakao** [comment]
I heard reports from two people with 3060s.
Patching in the latest linux-firmware from kernel.org fixed it for one person.
If someone else has this problem I will ask them to do that and report back here. 

But yeah, if there isn't anything soon then I'm totally fine with postponing this.

**Comment by mirkobrombin** [comment]
Sounds good

**Comment by mirkobrombin** [comment]
Planning for after stable but ready to pin it again for the stable in case
