### ISSUE TITLE
Disabling of GDM Wayland Rule Causes System To Freeze

### ISSUE THREAD

**Issue by MeDerpWasTaken** [Vanilla-OS/nvidia-image#41]
### Issue Description

When using this image, my screen freezes once GDM starts, and stays on that frame until I switch to a TTY and back, which will cause it to stay on that new frame. My mouse still works and I was able to login, but the issue continued. 

After some testing with a [modified version of the image](https://github.com/MeDerpWasTaken/nvidia-image), I discovered that it was the enable-wayland module that disabled the GDM wayland check rule that was causing the issue.

### Steps to Reproduce

1. Switch system to NVIDIA image with an NVIDIA GPU and reboot
2. Boot into the system (probably doesn't happen for everyone though)

### On what version of Vanilla OS this happens?

Stable

### Additional Information

GTX 1080ti with Ryzen 7700x, 1080p 165hz monitor

**Comment by MeDerpWasTaken** [comment]
It seems like if I try to start a GNOME Wayland session from my image, the same issue occurs, so maybe it's an issue with Wayland in general? Running weston in a window on X11 seems to work fine though

**Comment by Cjnator38** [comment]
I managed to get GDM to freeze adding `nvidia_drm.modeset=1` to kargs. Maybe that could be related to the issue?

**Comment by mirkobrombin** [comment]
I am using your image for testing, please keep the repo available for a while if possible.
