### ISSUE TITLE
3 monitor setup

### ISSUE THREAD

**Issue by onehumankindness** [Vanilla-OS/nvidia-image#44]
### Issue Description

The Kinetic version worked fine with this setup. Things I have tried: "Second monitor not working

If you have a second monitor connected to your NVIDIA GPU and it’s not working, you are probably using the wrong system image. To check the system image you are using, run the following command:

abroot status

and check the parameter Image under the ABImage section, it should be ghcr.io/vanilla-os/nvidia for recent NVIDIA GPUs (e.g. GTX 600 series/RTX and newer) or ghcr.io/vanilla-os/nvidia-propietary for older NVIDIA GPUs (e.g. GTX 400 and 500 series).

If you are not using the correct system image, you can change it by issuing the following command:

abroot config-editor

then change the tag parameter to main and the name parameter to ghcr.io/vanilla-os/nvidia or ghcr.io/vanilla-os/nvidia-propietary depending on your GPU as mentioned above. Then save the changes and run a system update by issuing the following command:

abroot upgrade -f

restart your system once the upgrade is complete." 

I tried the troubleshooting (https://docs.vanillaos.org/handbook/en/nvidia-issues#second-monitor-not-working)

![Screenshot from 2024-08-02 16-23-50](https://github.com/user-attachments/assets/099573b6-f7d1-4ff8-99a0-d247e6c38ce7)

### Steps to Reproduce

I think it's partition A.

### On what version of Vanilla OS this happens?

Vanilla OS 2 Orchid

### Additional Information

I saw the Distrowatch announcement and wonder if that might work. Also it seems that Kinetic had support for OBS Virtual Camera DKMS out of the box, was that deprecated or something? Just trying to get this machine up and running like your previous version ran out of the box. Thanks again for all your hard work

**Comment by onehumankindness** [comment]
After trying the Beta of Orchid on 2 different laptops and 1 desktop multiple times, as well as the new stable releases I had to move on to something that works out of the box like Kinetic did. I'll check back as I like the technology you have created. Thanks for the few who replied with things to try to get Orchid working.

**Comment by mirkobrombin** [comment]
related: https://github.com/Vanilla-OS/nvidia-image/issues/17
