### ISSUE TITLE
Enable KMS-Modifiers by default

### ISSUE THREAD

**Issue by msmafra** [Vanilla-OS/nvidia-image#51]
### Feature Description

As Xwayland is very important and won't go away anytime soon, enabling the kms-modifiers Gnome/Mutter feature should be the default.

### Rationale

It's a requirement on the NVIDIA documentation for the kms-modifiers to be enabled when using GNOME with Wayland to have rendering acceleration on Xwayland.

### Additional Information

It's a requirement since driver version 470.42.01 https://download.nvidia.com/XFree86/Linux-x86_64/560.28.03/README/xwayland.html

**Comment by axtloss** [comment]
Is there any reason why? I haven't experienced any issues without this and enabling experimental features out of the box isn't a good idea

**Comment by msmafra** [comment]
> Is there any reason why? I haven't experienced any issues without this and enabling experimental features out of the box isn't a good idea

I can only say that I don't know why it's still experimental (since 2021 ti seems), but even being experimental, is a requirement set by NVIDIA.

**Comment by axtloss** [comment]
Yes I do see that it is a requirement set by NVIDIA, but it still is an experimental feature and I don't see why it needs to be enabled, as I never had issues with it not being enabled

**Comment by msmafra** [comment]
As one of the users that used to have constant problems with NVIDIAon Wayland while listening to others saying that neer had problems, I never had issues with it enabled. I understand that being in the experimental section is a no no, but it still intrigs me that is a required feature. Thanks for your time.
