### ISSUE TITLE
Wayland Session Not Showing in GDM

### ISSUE THREAD

**Issue by MonsterObserver** [Vanilla-OS/nvidia-image#6]
To mitigate this, we either need to remove the GDM rules in `/usr/lib/udev/rules.d/61-gdm.rules`, or symlink it to NULL. (normally this can be overwritten by `/etc/udev/rules.d/61-gdm.rules`, but that directory does not exist.)

**Comment by mirkobrombin** [comment]
It’s working for me without any workaround
